In [4]:
import pandas as pd

In [68]:
with open("results.txt") as f:
    resultsraw = f.read()

In [69]:
print(resultsraw)

/akhorana
[ PASS ] NoMain
[ PASS ] NestedIf
[ PASS ] TwoClasses
[ PASS ] NewMain
[ FAIL ] MultipleErrorsCombined
Got error: 'b'Type violation in line 14\nType violation in line 15\nType violation in line 17\nType violation in line 18\n''
Expected : 'b'Type violation in line 14\nType violation in line 15\nType violation in line 16\nType violation in line 17\nType violation in line 18\n''
Run './parser /homes/cs352/Spring23/Grading/tarindu/p2test/tests/testcases/type/MultipleErrorsCombined.java'
[ PASS ] MultipleErrorsDoubleDecl
[ PASS ] StatementScopeRedefineSym
[ PASS ] LiteralExprIntToArray
[ FAIL ] StatementReturnWrongType
Got error: 'b'Type violation in line 7\n''
Expected : 'b'Type violation in line 6\n''
Run './parser /homes/cs352/Spring23/Grading/tarindu/p2test/tests/testcases/type/StatementReturnWrongType.java'
[ PASS ] UnaryExprUnaryBool
[ PASS ] StatementMethodCallWrongTypes
[ PASS ] StatementVarDeclCheckArgs
[ PASS ] LValExprDiffType
[ PASS ] ParseIntNotString
[ PASS ] MethodDeclWrongType
[ PASS ] StatementVarDeclRedefinition
[ PASS ] StatementScopeRedefinition
[ PASS ] BinaryExprLogicalToBool
[ PASS ] StaticVarDeclTypeStillRequired
[ PASS ] NewExprDifferentNewType
[ PASS ] BinaryExprIntInBool
[ PASS ] BinaryExprInvalidOperand
[ PASS ] LiteralExprBoolToInt
[ PASS ] StatementPrintBadExpr2
[ FAIL ] MultipleErrorsVarDecl
Got error: 'b'Type violation in line 19\nType violation in line 21\n''
Expected : 'b'Type violation in line 19\nType violation in line 20\nType violation in line 21\nType violation in line 21\nType violation in line 21\n''
Run './parser /homes/cs352/Spring23/Grading/tarindu/p2test/tests/testcases/type/MultipleErrorsVarDecl.java'
[ PASS ] MethodDeclBadReturnType
[ PASS ] StatementAssignWrongTypes
[ PASS ] MethodDeclAssignMethod2
[ PASS ] StatementPrintBadExpr
[ PASS ] MethodDeclBadExprInCall
[ PASS ] MethodDeclAssignMethod
[ PASS ] MethodDeclRedefinition
[ PASS ] MethodDeclTooFewArgs
[ PASS ] StatementAssignBadLValue
[ PASS ] UnaryExprNotEvalBool
[ PASS ] NewExprBoolInNew
[ PASS ] StaticVarDeclRedefinition
[ PASS ] NewExprArrayInNew
[ PASS ] LValExprTooManyBrackets
[ PASS ] MultipleErrorsStaticVars
[ PASS ] StatementAssignBadExpr
[ PASS ] StatementAssignBadLValue2
[ PASS ] MethodDeclAssignIntToBool
[ PASS ] StatementConditionalRecurseError
[ PASS ] UnaryExprLength
[ PASS ] UnaryExprUnaryString
[ PASS ] StatementConditionalWhile.NotBoolCond
[ PASS ] BinaryExprArrayInOp
[ PASS ] StatementConditionalIf.NotBoolCond
[ PASS ] UnaryExprNotInt
Ran 100 test. 0 syntax failures 3 type failures
####################

/hsu226
[ PASS ] NoMain
[ PASS ] NestedIf
[ PASS ] TwoClasses
[ PASS ] NewMain
[ PASS ] MultipleErrorsCombined
[ PASS ] MultipleErrorsDoubleDecl
[ PASS ] StatementScopeRedefineSym
[ PASS ] LiteralExprIntToArray
[ FAIL ] StatementReturnWrongType
Got error: 'b'''
Expected : 'b'Type violation in line 6\n''
Run './parser /homes/cs352/Spring23/Grading/tarindu/p2test/tests/testcases/type/StatementReturnWrongType.java'
[ PASS ] UnaryExprUnaryBool
[ FAIL ] StatementMethodCallWrongTypes
Got error: 'b'''
Expected : 'b'Type Violation in Line 7\n''
Run './parser /homes/cs352/Spring23/Grading/tarindu/p2test/tests/testcases/type/StatementMethodCallWrongTypes.java'
[ PASS ] StatementVarDeclCheckArgs
[ PASS ] LValExprDiffType
[ PASS ] ParseIntNotString
[ PASS ] MethodDeclWrongType
[ PASS ] StatementVarDeclRedefinition
[ PASS ] StatementScopeRedefinition
[ PASS ] BinaryExprLogicalToBool
[ PASS ] StaticVarDeclTypeStillRequired
[ PASS ] NewExprDifferentNewType
[ PASS ] BinaryExprIntInBool
[ PASS ] BinaryExprInvalidOperand
[ PASS ] LiteralExprBoolToInt
[ FAIL ] StatementPrintBadExpr2
Got error: 'b'''
Expected : 'b'Type violation in line 6\n''
Run './parser /homes/cs352/Spring23/Grading/tarindu/p2test/tests/testcases/type/StatementPrintBadExpr2.java'
[ PASS ] MultipleErrorsVarDecl
[ PASS ] MethodDeclBadReturnType
[ PASS ] StatementAssignWrongTypes
[ PASS ] MethodDeclAssignMethod2
[ PASS ] StatementPrintBadExpr
[ PASS ] MethodDeclBadExprInCall
[ PASS ] MethodDeclAssignMethod
[ PASS ] MethodDeclRedefinition
[ PASS ] MethodDeclTooFewArgs
[ PASS ] StatementAssignBadLValue
[ PASS ] UnaryExprNotEvalBool
[ PASS ] NewExprBoolInNew
[ PASS ] StaticVarDeclRedefinition
[ PASS ] NewExprArrayInNew
[ FAIL ] LValExprTooManyBrackets
Got error: 'b'Type violation in line 6\nType violation in line 6\n''
Expected : 'b'Type violation in line 6\n''
Run './parser /homes/cs352/Spring23/Grading/tarindu/p2test/tests/testcases/type/LValExprTooManyBrackets.java'
[ PASS ] MultipleErrorsStaticVars
[ PASS ] StatementAssignBadExpr
[ PASS ] StatementAssignBadLValue2
[ PASS ] MethodDeclAssignIntToBool
[ PASS ] StatementConditionalRecurseError
[ PASS ] UnaryExprLength
[ PASS ] UnaryExprUnaryString
[ PASS ] StatementConditionalWhile.NotBoolCond
[ PASS ] BinaryExprArrayInOp
[ PASS ] StatementConditionalIf.NotBoolCond
[ PASS ] UnaryExprNotInt
Ran 100 test. 0 syntax failures 4 type failures
####################

/wangej
[ PASS ] NoMain
[ PASS ] NestedIf
[ PASS ] TwoClasses
[ PASS ] NewMain
[ FAIL ] MultipleErrorsCombined
Got error: 'b'Type violation in line 14\nType violation in line 16\nType violation in line 17\nType violation in line 18\n''
Expected : 'b'Type violation in line 14\nType violation in line 15\nType violation in line 16\nType violation in line 17\nType violation in line 18\n''
Run './parser /homes/cs352/Spring23/Grading/tarindu/p2test/tests/testcases/type/MultipleErrorsCombined.java'
[ PASS ] MultipleErrorsDoubleDecl
[ PASS ] StatementScopeRedefineSym
[ PASS ] LiteralExprIntToArray
[ PASS ] StatementReturnWrongType
[ PASS ] UnaryExprUnaryBool
[ PASS ] StatementMethodCallWrongTypes
[ PASS ] StatementVarDeclCheckArgs
[ PASS ] LValExprDiffType
[ PASS ] ParseIntNotString
[ PASS ] MethodDeclWrongType
[ PASS ] StatementVarDeclRedefinition
[ PASS ] StatementScopeRedefinition
[ PASS ] BinaryExprLogicalToBool
[ PASS ] StaticVarDeclTypeStillRequired
[ PASS ] NewExprDifferentNewType
[ PASS ] BinaryExprIntInBool
[ PASS ] BinaryExprInvalidOperand
[ PASS ] LiteralExprBoolToInt
[ PASS ] StatementPrintBadExpr2
[ FAIL ] MultipleErrorsVarDecl
Got error: 'b'Type violation in line 19\nType violation in line 20\n''
Expected : 'b'Type violation in line 19\nType violation in line 20\nType violation in line 21\nType violation in line 21\nType violation in line 21\n''
Run './parser /homes/cs352/Spring23/Grading/tarindu/p2test/tests/testcases/type/MultipleErrorsVarDecl.java'
[ PASS ] MethodDeclBadReturnType
[ PASS ] StatementAssignWrongTypes
[ PASS ] MethodDeclAssignMethod2
[ PASS ] StatementPrintBadExpr
[ PASS ] MethodDeclBadExprInCall
[ PASS ] MethodDeclAssignMethod
[ PASS ] MethodDeclRedefinition
[ PASS ] MethodDeclTooFewArgs
[ PASS ] StatementAssignBadLValue
[ FAIL ] UnaryExprNotEvalBool
Got error: 'b'''
Expected : 'b'Type violation in line 5\n''
Run './parser /homes/cs352/Spring23/Grading/tarindu/p2test/tests/testcases/type/UnaryExprNotEvalBool.java'
[ PASS ] NewExprBoolInNew
[ PASS ] StaticVarDeclRedefinition
[ PASS ] NewExprArrayInNew
[ PASS ] LValExprTooManyBrackets
[ FAIL ] MultipleErrorsStaticVars
Got error: 'b'Type violation in line 8\n''
Expected : 'b'Type violation in line 8\nType violation in line 9\n''
Run './parser /homes/cs352/Spring23/Grading/tarindu/p2test/tests/testcases/type/MultipleErrorsStaticVars.java'
[ PASS ] StatementAssignBadExpr
[ PASS ] StatementAssignBadLValue2
[ PASS ] MethodDeclAssignIntToBool
[ PASS ] StatementConditionalRecurseError
[ PASS ] UnaryExprLength
[ PASS ] UnaryExprUnaryString
[ PASS ] StatementConditionalWhile.NotBoolCond
[ PASS ] BinaryExprArrayInOp
[ PASS ] StatementConditionalIf.NotBoolCond
[ PASS ] UnaryExprNotInt
Ran 100 test. 0 syntax failures 4 type failures
####################

/brupp
[ PASS ] NoMain
[ PASS ] NestedIf
[ PASS ] TwoClasses
[ PASS ] NewMain
[ PASS ] MultipleErrorsCombined
[ PASS ] MultipleErrorsDoubleDecl
[ PASS ] StatementScopeRedefineSym
[ PASS ] LiteralExprIntToArray
[ FAIL ] StatementReturnWrongType
Got error: 'b'''
Expected : 'b'Type violation in line 6\n''
Run './parser /homes/cs352/Spring23/Grading/tarindu/p2test/tests/testcases/type/StatementReturnWrongType.java'
[ PASS ] UnaryExprUnaryBool
[ PASS ] StatementMethodCallWrongTypes
[ PASS ] StatementVarDeclCheckArgs
[ PASS ] LValExprDiffType
[ PASS ] ParseIntNotString
[ PASS ] MethodDeclWrongType
[ PASS ] StatementVarDeclRedefinition
[ PASS ] StatementScopeRedefinition
[ PASS ] BinaryExprLogicalToBool
[ FAIL ] StaticVarDeclTypeStillRequired
Got error: 'b'''
Expected : 'b'Type violation in line 5\n''
Run './parser /homes/cs352/Spring23/Grading/tarindu/p2test/tests/testcases/type/StaticVarDeclTypeStillRequired.java'
[ PASS ] NewExprDifferentNewType
[ PASS ] BinaryExprIntInBool
[ PASS ] BinaryExprInvalidOperand
[ PASS ] LiteralExprBoolToInt
[ PASS ] StatementPrintBadExpr2
[ FAIL ] MultipleErrorsVarDecl
Got error: 'b'Type violation in line 19\nType violation in line 20\nType violation in line 21\n''
Expected : 'b'Type violation in line 19\nType violation in line 20\nType violation in line 21\nType violation in line 21\nType violation in line 21\n''
Run './parser /homes/cs352/Spring23/Grading/tarindu/p2test/tests/testcases/type/MultipleErrorsVarDecl.java'
[ PASS ] MethodDeclBadReturnType
[ PASS ] StatementAssignWrongTypes
[ PASS ] MethodDeclAssignMethod2
[ PASS ] StatementPrintBadExpr
[ PASS ] MethodDeclBadExprInCall
[ PASS ] MethodDeclAssignMethod
[ PASS ] MethodDeclRedefinition
[ PASS ] MethodDeclTooFewArgs
[ PASS ] StatementAssignBadLValue
[ PASS ] UnaryExprNotEvalBool
[ PASS ] NewExprBoolInNew
[ PASS ] StaticVarDeclRedefinition
[ PASS ] NewExprArrayInNew
[ PASS ] LValExprTooManyBrackets
[ PASS ] MultipleErrorsStaticVars
[ PASS ] StatementAssignBadExpr
[ PASS ] StatementAssignBadLValue2
[ PASS ] MethodDeclAssignIntToBool
[ PASS ] StatementConditionalRecurseError
[ PASS ] UnaryExprLength
[ PASS ] UnaryExprUnaryString
[ PASS ] StatementConditionalWhile.NotBoolCond
[ PASS ] BinaryExprArrayInOp
[ PASS ] StatementConditionalIf.NotBoolCond
[ PASS ] UnaryExprNotInt
Ran 100 test. 0 syntax failures 3 type failures
####################

/kong98
[ PASS ] NoMain
[ PASS ] NestedIf
[ PASS ] TwoClasses
[ PASS ] NewMain
[ PASS ] MultipleErrorsCombined
[ PASS ] MultipleErrorsDoubleDecl
[ PASS ] StatementScopeRedefineSym
[ PASS ] LiteralExprIntToArray
[ FAIL ] StatementReturnWrongType
Got error: 'b'''
Expected : 'b'Type violation in line 6\n''
Run './parser /homes/cs352/Spring23/Grading/tarindu/p2test/tests/testcases/type/StatementReturnWrongType.java'
[ PASS ] UnaryExprUnaryBool
[ FAIL ] StatementMethodCallWrongTypes
Got error: 'b'''
Expected : 'b'Type Violation in Line 7\n''
Run './parser /homes/cs352/Spring23/Grading/tarindu/p2test/tests/testcases/type/StatementMethodCallWrongTypes.java'
[ PASS ] StatementVarDeclCheckArgs
[ PASS ] LValExprDiffType
[ PASS ] ParseIntNotString
[ PASS ] MethodDeclWrongType
[ PASS ] StatementVarDeclRedefinition
[ PASS ] StatementScopeRedefinition
[ PASS ] BinaryExprLogicalToBool
[ PASS ] StaticVarDeclTypeStillRequired
[ PASS ] NewExprDifferentNewType
[ PASS ] BinaryExprIntInBool
[ PASS ] BinaryExprInvalidOperand
[ PASS ] LiteralExprBoolToInt
[ PASS ] StatementPrintBadExpr2
[ FAIL ] MultipleErrorsVarDecl
Got error: 'b'Type Violation in Line 19\nType Violation in Line 20\nType Violation in Line 21\nType Violation in Line 21\nType Violation in Line 21\nType Violation in Line 21\nType Violation in Line 21\nType Violation in Line 21\nType Violation in Line 21\nType Violation in Line 21\n''
Expected : 'b'Type violation in line 19\nType violation in line 20\nType violation in line 21\nType violation in line 21\nType violation in line 21\n''
Run './parser /homes/cs352/Spring23/Grading/tarindu/p2test/tests/testcases/type/MultipleErrorsVarDecl.java'
[ PASS ] MethodDeclBadReturnType
[ PASS ] StatementAssignWrongTypes
[ FAIL ] MethodDeclAssignMethod2
Got error: 'b'Type Violation in Line 5\nType Violation in Line 5\n''
Expected : 'b'Type violation in line 5\n''
Run './parser /homes/cs352/Spring23/Grading/tarindu/p2test/tests/testcases/type/MethodDeclAssignMethod2.java'
[ PASS ] StatementPrintBadExpr
[ PASS ] MethodDeclBadExprInCall
[ FAIL ] MethodDeclAssignMethod
Got error: 'b'Type Violation in Line 5\nType Violation in Line 5\n''
Expected : 'b'Type violation in line 5\n''
Run './parser /homes/cs352/Spring23/Grading/tarindu/p2test/tests/testcases/type/MethodDeclAssignMethod.java'
[ FAIL ] MethodDeclRedefinition
Got error: 'b'''
Expected : 'b'Type violation in line 6\n''
Run './parser /homes/cs352/Spring23/Grading/tarindu/p2test/tests/testcases/type/MethodDeclRedefinition.java'
[ PASS ] MethodDeclTooFewArgs
[ FAIL ] StatementAssignBadLValue
Got error: 'b'Type Violation in Line 7\nType Violation in Line 7\nType Violation in Line 7\n''
Expected : 'b'Type violation in line 7\n''
Run './parser /homes/cs352/Spring23/Grading/tarindu/p2test/tests/testcases/type/StatementAssignBadLValue.java'
[ PASS ] UnaryExprNotEvalBool
[ PASS ] NewExprBoolInNew
[ PASS ] StaticVarDeclRedefinition
[ PASS ] NewExprArrayInNew
[ FAIL ] LValExprTooManyBrackets
Got error: 'b'''
Expected : 'b'Type violation in line 6\n''
Run './parser /homes/cs352/Spring23/Grading/tarindu/p2test/tests/testcases/type/LValExprTooManyBrackets.java'
[ PASS ] MultipleErrorsStaticVars
[ FAIL ] StatementAssignBadExpr
Got error: 'b'Type Violation in Line 9\nType Violation in Line 9\n''
Expected : 'b'Type violation in line 9\n''
Run './parser /homes/cs352/Spring23/Grading/tarindu/p2test/tests/testcases/type/StatementAssignBadExpr.java'
[ PASS ] StatementAssignBadLValue2
[ PASS ] MethodDeclAssignIntToBool
[ PASS ] StatementConditionalRecurseError
[ PASS ] UnaryExprLength
[ PASS ] UnaryExprUnaryString
[ PASS ] StatementConditionalWhile.NotBoolCond
[ FAIL ] BinaryExprArrayInOp
Got error: 'b'Type Violation in Line 7\nType Violation in Line 7\n''
Expected : 'b'Type violation in line 7\n''
Run './parser /homes/cs352/Spring23/Grading/tarindu/p2test/tests/testcases/type/BinaryExprArrayInOp.java'
[ PASS ] StatementConditionalIf.NotBoolCond
[ PASS ] UnaryExprNotInt
Ran 100 test. 0 syntax failures 10 type failures
####################

/menonk
[ PASS ] NoMain
[ PASS ] NestedIf
[ PASS ] TwoClasses
[ PASS ] NewMain
[ PASS ] MultipleErrorsCombined
[ PASS ] MultipleErrorsDoubleDecl
[ PASS ] StatementScopeRedefineSym
[ PASS ] LiteralExprIntToArray
[ PASS ] StatementReturnWrongType
[ PASS ] UnaryExprUnaryBool
[ PASS ] StatementMethodCallWrongTypes
[ FAIL ] StatementVarDeclCheckArgs
Got error: 'b'''
Expected : 'b'Type violation in line 6\n''
Run './parser /homes/cs352/Spring23/Grading/tarindu/p2test/tests/testcases/type/StatementVarDeclCheckArgs.java'
[ PASS ] LValExprDiffType
[ PASS ] ParseIntNotString
[ PASS ] MethodDeclWrongType
[ PASS ] StatementVarDeclRedefinition
[ PASS ] StatementScopeRedefinition
[ PASS ] BinaryExprLogicalToBool
[ PASS ] StaticVarDeclTypeStillRequired
[ PASS ] NewExprDifferentNewType
[ PASS ] BinaryExprIntInBool
[ PASS ] BinaryExprInvalidOperand
[ PASS ] LiteralExprBoolToInt
[ PASS ] StatementPrintBadExpr2
[ PASS ] MultipleErrorsVarDecl
[ PASS ] MethodDeclBadReturnType
[ PASS ] StatementAssignWrongTypes
[ PASS ] MethodDeclAssignMethod2
[ PASS ] StatementPrintBadExpr
[ FAIL ] MethodDeclBadExprInCall
Got error: 'b'Type violation in line 8\nType violation in line 8\n''
Expected : 'b'Type violation in line 8\n''
Run './parser /homes/cs352/Spring23/Grading/tarindu/p2test/tests/testcases/type/MethodDeclBadExprInCall.java'
[ PASS ] MethodDeclAssignMethod
[ PASS ] MethodDeclRedefinition
[ PASS ] MethodDeclTooFewArgs
[ PASS ] StatementAssignBadLValue
[ PASS ] UnaryExprNotEvalBool
[ PASS ] NewExprBoolInNew
[ PASS ] StaticVarDeclRedefinition
[ PASS ] NewExprArrayInNew
[ PASS ] LValExprTooManyBrackets
[ PASS ] MultipleErrorsStaticVars
[ FAIL ] StatementAssignBadExpr
Got error: 'b'Type violation in line 9\nType violation in line 9\n''
Expected : 'b'Type violation in line 9\n''
Run './parser /homes/cs352/Spring23/Grading/tarindu/p2test/tests/testcases/type/StatementAssignBadExpr.java'
[ FAIL ] StatementAssignBadLValue2
Got error: 'b'Type violation in line 6\nType violation in line 6\n''
Expected : 'b'Type Violation in Line 6\n''
Run './parser /homes/cs352/Spring23/Grading/tarindu/p2test/tests/testcases/type/StatementAssignBadLValue2.java'
[ PASS ] MethodDeclAssignIntToBool
[ PASS ] StatementConditionalRecurseError
[ PASS ] UnaryExprLength
[ PASS ] UnaryExprUnaryString
[ PASS ] StatementConditionalWhile.NotBoolCond
[ PASS ] BinaryExprArrayInOp
[ PASS ] StatementConditionalIf.NotBoolCond
[ PASS ] UnaryExprNotInt
Ran 100 test. 0 syntax failures 4 type failures
####################

/ihpatel
[ PASS ] NoMain
[ PASS ] NestedIf
[ PASS ] TwoClasses
[ PASS ] NewMain
[ FAIL ] MultipleErrorsCombined
Got error: 'b'Type Violation in Line 14\nType Violation in Line 15\n''
Expected : 'b'Type violation in line 14\nType violation in line 15\nType violation in line 16\nType violation in line 17\nType violation in line 18\n''
Run './parser /homes/cs352/Spring23/Grading/tarindu/p2test/tests/testcases/type/MultipleErrorsCombined.java'
[ PASS ] MultipleErrorsDoubleDecl
[ PASS ] StatementScopeRedefineSym
[ FAIL ] LiteralExprIntToArray
Got error: 'b'Type Violation in Line 4\nType Violation in Line 4\n''
Expected : 'b'Type violation in line 4\n''
Run './parser /homes/cs352/Spring23/Grading/tarindu/p2test/tests/testcases/type/LiteralExprIntToArray.java'
[ FAIL ] StatementReturnWrongType
Got error: 'b'''
Expected : 'b'Type violation in line 6\n''
Run './parser /homes/cs352/Spring23/Grading/tarindu/p2test/tests/testcases/type/StatementReturnWrongType.java'
[ PASS ] UnaryExprUnaryBool
[ FAIL ] StatementMethodCallWrongTypes
Got error: 'b'''
Expected : 'b'Type Violation in Line 7\n''
Run './parser /homes/cs352/Spring23/Grading/tarindu/p2test/tests/testcases/type/StatementMethodCallWrongTypes.java'
[ FAIL ] StatementVarDeclCheckArgs
Got error: 'b'''
Expected : 'b'Type violation in line 6\n''
Run './parser /homes/cs352/Spring23/Grading/tarindu/p2test/tests/testcases/type/StatementVarDeclCheckArgs.java'
[ FAIL ] LValExprDiffType
Got error: 'b'Type Violation in Line 6\nType Violation in Line 6\n''
Expected : 'b'Type violation in line 6\n''
Run './parser /homes/cs352/Spring23/Grading/tarindu/p2test/tests/testcases/type/LValExprDiffType.java'
[ FAIL ] ParseIntNotString
Got error: 'b'Type Violation in Line 6\nType Violation in Line 6\n''
Expected : 'b'Type violation in line 6\n''
Run './parser /homes/cs352/Spring23/Grading/tarindu/p2test/tests/testcases/type/ParseIntNotString.java'
[ FAIL ] MethodDeclWrongType
Got error: 'b'Type Violation in Line 5\nType Violation in Line 5\n''
Expected : 'b'Type violation in line 5\n''
Run './parser /homes/cs352/Spring23/Grading/tarindu/p2test/tests/testcases/type/MethodDeclWrongType.java'
[ PASS ] StatementVarDeclRedefinition
[ PASS ] StatementScopeRedefinition
[ FAIL ] BinaryExprLogicalToBool
Got error: 'b'Type Violation in Line 5\nType Violation in Line 5\n''
Expected : 'b'Type violation in line 5\n''
Run './parser /homes/cs352/Spring23/Grading/tarindu/p2test/tests/testcases/type/BinaryExprLogicalToBool.java'
[ FAIL ] StaticVarDeclTypeStillRequired
Got error: 'b'''
Expected : 'b'Type violation in line 5\n''
Run './parser /homes/cs352/Spring23/Grading/tarindu/p2test/tests/testcases/type/StaticVarDeclTypeStillRequired.java'
[ FAIL ] NewExprDifferentNewType
Got error: 'b'Type Violation in Line 5\nType Violation in Line 5\n''
Expected : 'b'Type violation in line 5\n''
Run './parser /homes/cs352/Spring23/Grading/tarindu/p2test/tests/testcases/type/NewExprDifferentNewType.java'
[ PASS ] BinaryExprIntInBool
[ FAIL ] BinaryExprInvalidOperand
Got error: 'b'''
Expected : 'b'Type violation in line 6\n''
Run './parser /homes/cs352/Spring23/Grading/tarindu/p2test/tests/testcases/type/BinaryExprInvalidOperand.java'
[ PASS ] LiteralExprBoolToInt
[ FAIL ] StatementPrintBadExpr2
Got error: 'b'''
Expected : 'b'Type violation in line 6\n''

In [70]:
results = resultsraw.split("####################")

In [71]:
names = []
syntaxpoints = []
typepoints = []
feedbacks = []

for u in results:
    try:
        ulist = u.strip().split("\n")
        name = ulist[0][1:]
        synpoint = (50-int(ulist[-1].split()[3]))
        typpoint = (50-int(ulist[-1].split()[6]))
        feedback = "\n".join(ulist[1:-1])
        names.append(name)
        syntaxpoints.append(synpoint)
        typepoints.append(typpoint)
        feedbacks.append(feedback)
    except:
        continue

In [73]:
marks = pd.DataFrame({"name": names, "syntaxpoints": syntaxpoints, "typepoints": typepoints, "feedback": feedbacks})

In [74]:
marks

,name,syntaxpoints,typepoints,feedback
0,akhorana,50,47,[ PASS ] NoMain\n[ PASS ] Ne...
1,hsu226,50,46,[ PASS ] NoMain\n[ PASS ] Ne...
2,wangej,50,46,[ PASS ] NoMain\n[ PASS ] Ne...
3,brupp,50,47,[ PASS ] NoMain\n[ PASS ] Ne...
4,kong98,50,40,[ PASS ] NoMain\n[ PASS ] Ne...
5,menonk,50,46,[ PASS ] NoMain\n[ PASS ] Ne...
6,ihpatel,50,20,[ PASS ] NoMain\n[ PASS ] Ne...
7,jain385,50,48,[ PASS ] NoMain\n[ PASS ] Ne...
8,zhu862,2,2,[ PASS ] NoMain\n[ FAIL ] Ne...
9,aneema,50,50,[ PASS ] NoMain\n[ PASS ] Ne...
10,mpietran,50,39,[ PASS ] NoMain\n[ PASS ] Ne...
11,szapodea,50,43,[ PASS ] NoMain\n[ PASS ] Ne...
12,jensen97,50,4,[ PASS ] NoMain\n[ PASS ] Ne...
13,edetoled,46,27,[ PASS ] NoMain\n[ FAIL ] Ne...
14,li3327,2,2,[ PASS ] NoMain\n[ FAIL ] Ne...
15,yberg,50,45,[ PASS ] NoMain\n[ PASS ] Ne...
16,choi493,16,4,[ PASS ] NoMain\n[ PASS ] Ne...
17,kang377,50,46,[ PASS ] NoMain\n[ PASS ] Ne...
18,gupta565,49,36,[ PASS ] NoMain\n[ PASS ] Ne...
19,mdsantia,50,43,[ PASS ] NoMain\n[ PASS ] Ne...
20,ndullam,50,46,[ PASS ] NoMain\n[ PASS ] Ne...
21,gala0,50,48,[ PASS ] NoMain\n[ PASS ] Ne...
22,rnstump,49,43,[ FAIL ] NoMain\nMainClass: Test1\n| ...
23,ehli,50,4,[ PASS ] NoMain\n[ PASS ] Ne...
24,eafalck,50,46,[ PASS ] NoMain\n[ PASS ] Ne...
25,tmattil,49,43,[ PASS ] NoMain\n[ PASS ] Ne...
26,mason143,50,43,[ PASS ] NoMain\n[ PASS ] Ne...
27,rdelliso,50,44,[ PASS ] NoMain\n[ PASS ] Ne...
28,zhou977,49,44,[ PASS ] NoMain\n[ PASS ] Ne...
29,sharm535,0,0,[ FAIL ] NoMain\nGot error: 'b'Syntax...
30,kim2942,50,50,[ PASS ] NoMain\n[ PASS ] Ne...
31,amelachu,50,50,[ PASS ] NoMain\n[ PASS ] Ne...
32,mccarth,50,45,[ PASS ] NoMain\n[ PASS ] Ne...
33,abhullar,50,4,[ PASS ] NoMain\n[ PASS ] Ne...
34,zhan4150,50,48,[ PASS ] NoMain\n[ PASS ] Ne...
35,sun1017,50,40,[ PASS ] NoMain\n[ PASS ] Ne...
36,wu1542,50,14,[ PASS ] NoMain\n[ PASS ] Ne...
37,heise4,46,43,[ PASS ] NoMain\n[ PASS ] Ne...
38,yang1800,50,43,[ PASS ] NoMain\n[ PASS ] Ne...
39,adusi,50,48,[ PASS ] NoMain\n[ PASS ] Ne...
40,akute,50,48,[ PASS ] NoMain\n[ PASS ] Ne...
41,jpha,48,30,[ PASS ] NoMain\n[ PASS ] Ne...
42,jchustak,50,40,[ PASS ] NoMain\n[ PASS ] Ne...
43,upadhya4,49,24,[ PASS ] NoMain\n[ PASS ] Ne...
44,ding256,50,48,[ PASS ] NoMain\n[ PASS ] Ne...
45,singh726,49,37,[ PASS ] NoMain\n[ PASS ] Ne...
46,mtejeda,50,37,[ PASS ] NoMain\n[ PASS ] Ne...
47,agazda,50,45,[ PASS ] NoMain\n[ PASS ] Ne...
48,lee3380,50,44,[ PASS ] NoMain\n[ PASS ] Ne...
49,yyegorov,49,4,[ PASS ] NoMain\n[ PASS ] Ne...
50,skharban,50,33,[ PASS ] NoMain\n[ PASS ] Ne...
51,aravadha,50,4,[ PASS ] NoMain\n[ PASS ] Ne...

In [75]:
with open("submitdates.txt") as f:
    submitdates = f.read()

In [76]:
submitdateslist = submitdates.strip().split("\n")

In [77]:
dnames = []
dates = []
times = []

for sub in submitdateslist:
    subl = sub.split()
    name = subl[0][:-2]
    date = subl[4]
    time = subl[5][:8]
    dnames.append(name)
    dates.append(date)
    times.append(time)
  

subdates = pd.DataFrame({"name": dnames, "date": dates, "times": times})

In [78]:
merged = subdates.merge(marks, on='name', how='outer')

In [79]:
merged.to_csv("grades.csv", index=False)

In [80]:
merged

,name,date,times,syntaxpoints,typepoints,feedback
0,abhullar,2023-03-12,19:37:54,50.0,4.0,[ PASS ] NoMain\n[ PASS ] Ne...
1,adusi,2023-03-07,12:09:29,50.0,48.0,[ PASS ] NoMain\n[ PASS ] Ne...
2,agazda,2023-03-12,23:23:53,50.0,45.0,[ PASS ] NoMain\n[ PASS ] Ne...
3,akhorana,2023-03-12,00:53:10,50.0,47.0,[ PASS ] NoMain\n[ PASS ] Ne...
4,akute,2023-03-08,17:49:22,50.0,48.0,[ PASS ] NoMain\n[ PASS ] Ne...
5,amelachu,2023-03-11,16:19:11,50.0,50.0,[ PASS ] NoMain\n[ PASS ] Ne...
6,aneema,2023-03-10,17:35:01,50.0,50.0,[ PASS ] NoMain\n[ PASS ] Ne...
7,aravadha,2023-03-12,21:38:02,50.0,4.0,[ PASS ] NoMain\n[ PASS ] Ne...
8,brupp,2023-03-15,23:59:40,50.0,47.0,[ PASS ] NoMain\n[ PASS ] Ne...
9,choi493,2023-03-14,22:54:58,16.0,4.0,[ PASS ] NoMain\n[ PASS ] Ne...
10,ding256,2023-03-15,22:56:01,50.0,48.0,[ PASS ] NoMain\n[ PASS ] Ne...
11,eafalck,2023-03-08,19:21:44,50.0,46.0,[ PASS ] NoMain\n[ PASS ] Ne...
12,edetoled,2023-03-13,23:43:02,46.0,27.0,[ PASS ] NoMain\n[ FAIL ] Ne...
13,ehli,2023-03-15,23:54:27,50.0,4.0,[ PASS ] NoMain\n[ PASS ] Ne...
14,gala0,2023-03-08,20:26:40,50.0,48.0,[ PASS ] NoMain\n[ PASS ] Ne...
15,gupta565,2023-03-13,23:35:51,49.0,36.0,[ PASS ] NoMain\n[ PASS ] Ne...
16,harve106,2023-03-09,15:07:31,NaN,NaN,NaN
17,heise4,2023-03-12,23:58:25,46.0,43.0,[ PASS ] NoMain\n[ PASS ] Ne...
18,hsu226,2023-03-12,23:50:17,50.0,46.0,[ PASS ] NoMain\n[ PASS ] Ne...
19,ihpatel,2023-03-08,17:49:14,50.0,20.0,[ PASS ] NoMain\n[ PASS ] Ne...
20,jain385,2023-03-08,21:52:12,50.0,48.0,[ PASS ] NoMain\n[ PASS ] Ne...
21,jchustak,2023-03-15,23:58:02,50.0,40.0,[ PASS ] NoMain\n[ PASS ] Ne...
22,jensen97,2023-03-15,23:53:51,50.0,4.0,[ PASS ] NoMain\n[ PASS ] Ne...
23,jpha,2023-03-15,23:57:41,48.0,30.0,[ PASS ] NoMain\n[ PASS ] Ne...
24,kang377,2023-03-12,22:26:04,50.0,46.0,[ PASS ] NoMain\n[ PASS ] Ne...
25,kim2942,2023-03-08,12:36:50,50.0,50.0,[ PASS ] NoMain\n[ PASS ] Ne...
26,kong98,2023-03-08,22:55:48,50.0,40.0,[ PASS ] NoMain\n[ PASS ] Ne...
27,lee3380,2023-03-08,19:04:25,50.0,44.0,[ PASS ] NoMain\n[ PASS ] Ne...
28,li3327,2023-03-13,21:23:22,2.0,2.0,[ PASS ] NoMain\n[ FAIL ] Ne...
29,mason143,2023-03-13,22:07:03,50.0,43.0,[ PASS ] NoMain\n[ PASS ] Ne...
30,mccarth,2023-03-12,23:22:58,50.0,45.0,[ PASS ] NoMain\n[ PASS ] Ne...
31,mdsantia,2023-03-15,23:57:14,50.0,43.0,[ PASS ] NoMain\n[ PASS ] Ne...
32,menonk,2023-03-13,20:44:19,50.0,46.0,[ PASS ] NoMain\n[ PASS ] Ne...
33,miao29,2023-03-12,23:41:30,NaN,NaN,NaN
34,mpietran,2023-03-15,23:58:57,50.0,39.0,[ PASS ] NoMain\n[ PASS ] Ne...
35,mtejeda,2023-03-11,19:37:13,50.0,37.0,[ PASS ] NoMain\n[ PASS ] Ne...
36,ndullam,2023-03-12,20:02:57,50.0,46.0,[ PASS ] NoMain\n[ PASS ] Ne...
37,rdelliso,2023-03-12,21:49:53,50.0,44.0,[ PASS ] NoMain\n[ PASS ] Ne...
38,rnstump,2023-03-14,23:48:07,49.0,43.0,[ FAIL ] NoMain\nMainClass: Test1\n| ...
39,sharm390,2023-03-16,00:01:11,NaN,NaN,NaN
40,sharm535,2023-03-12,17:07:53,0.0,0.0,[ FAIL ] NoMain\nGot error: 'b'Syntax...
41,singh726,2023-03-08,20:11:36,49.0,37.0,[ PASS ] NoMain\n[ PASS ] Ne...
42,skharban,2023-03-13,23:24:21,50.0,33.0,[ PASS ] NoMain\n[ PASS ] Ne...
43,sun1017,2023-03-13,22:55:02,50.0,40.0,[ PASS ] NoMain\n[ PASS ] Ne...
44,szapodea,2023-03-14,19:33:17,50.0,43.0,[ PASS ] NoMain\n[ PASS ] Ne...
45,tmattil,2023-03-13,23:34:33,49.0,43.0,[ PASS ] NoMain\n[ PASS ] Ne...
46,upadhya4,2023-03-12,18:59:55,49.0,24.0,[ PASS ] NoMain\n[ PASS ] Ne...
47,verma119,2023-03-12,23:45:23,NaN,NaN,NaN
48,wangej,2023-03-08,13:37:15,50.0,46.0,[ PASS ] NoMain\n[ PASS ] Ne...
49,wu1542,2023-03-12,20:51:36,50.0,14.0,[ PASS ] NoMain\n[ PASS ] Ne...
50,yang1800,2023-03-15,16:15:17,50.0,43.0,[ PASS ] NoMain\n[ PASS ] Ne...
51,yberg,2023-03-14,17:10:39,50.0,45.0,[ PASS ] NoMain\n[ PASS ] Ne...
52,yyegorov,2023-03-09,20:02:43,49.0,4.0,[ PASS ] NoMain\n[ PASS ] Ne...
53,zhan4150,2023-03-12,18:05:54,50.0,48.0,[ PASS ] NoMain\n[ PASS ] Ne...
54,zhou977,2023-03-11,12:38:37,49.0,44.0,[ PASS ] NoMain\n[ PASS ] Ne...
55,zhu862,2023-03-15,23:51:58,2.0,2.0,[ PASS ] NoMain\n[ FAIL ] Ne...

In [81]:
p2grades = pd.read_csv("p2grades.csv")

In [82]:
p2grades

,name,date,times,syntaxpoints,typepoints,latedays,bonus,total
0,abhullar,3/12/23,19:37:54,50.0,4.0,0.0,0.0,54.0
1,adusi,3/7/23,12:09:29,50.0,48.0,-5.0,4.0,102.0
2,agazda,3/12/23,23:23:53,50.0,45.0,0.0,0.0,95.0
3,akhorana,3/12/23,0:53:10,50.0,47.0,0.0,0.0,97.0
4,akute,3/8/23,17:49:22,50.0,48.0,-4.0,4.0,102.0
5,amelachu,3/11/23,16:19:11,50.0,50.0,-1.0,0.0,100.0
6,aneema,3/10/23,17:35:01,50.0,50.0,-2.0,0.0,100.0
7,aravadha,3/12/23,21:38:02,50.0,4.0,0.0,0.0,54.0
8,brupp,3/15/23,23:59:40,50.0,47.0,3.0,0.0,97.0
9,choi493,3/14/23,22:54:58,16.0,4.0,2.0,0.0,20.0
10,ding256,3/15/23,22:56:01,50.0,48.0,3.0,0.0,98.0
11,eafalck,3/8/23,19:21:44,50.0,46.0,-4.0,4.0,100.0
12,edetoled,3/13/23,23:43:02,46.0,27.0,1.0,0.0,73.0
13,ehli,3/15/23,23:54:27,50.0,4.0,3.0,0.0,54.0
14,gala0,3/8/23,20:26:40,50.0,48.0,-4.0,4.0,102.0
15,gupta565,3/13/23,23:35:51,49.0,36.0,1.0,0.0,85.0
16,harve106,3/9/23,15:07:31,NaN,NaN,-3.0,0.0,0.0
17,heise4,3/12/23,23:58:25,46.0,43.0,0.0,0.0,89.0
18,hsu226,3/12/23,23:50:17,50.0,46.0,0.0,0.0,96.0
19,ihpatel,3/8/23,17:49:14,50.0,20.0,-4.0,4.0,74.0
20,jain385,3/8/23,21:52:12,50.0,48.0,-4.0,4.0,102.0
21,jchustak,3/15/23,23:58:02,50.0,40.0,3.0,0.0,90.0
22,jensen97,3/15/23,23:53:51,50.0,4.0,3.0,0.0,54.0
23,jpha,3/15/23,23:57:41,48.0,30.0,3.0,0.0,78.0
24,kang377,3/12/23,22:26:04,50.0,46.0,0.0,0.0,96.0
25,kim2942,3/8/23,12:36:50,50.0,50.0,-4.0,4.0,104.0
26,kong98,3/8/23,22:55:48,50.0,40.0,-4.0,4.0,94.0
27,lee3380,3/8/23,19:04:25,50.0,44.0,-4.0,4.0,98.0
28,li3327,3/13/23,21:23:22,2.0,2.0,1.0,0.0,4.0
29,mason143,3/13/23,22:07:03,50.0,43.0,1.0,0.0,93.0
30,mccarth,3/12/23,23:22:58,50.0,45.0,0.0,0.0,95.0
31,mdsantia,3/15/23,23:57:14,50.0,43.0,3.0,0.0,93.0
32,menonk,3/13/23,20:44:19,50.0,46.0,1.0,0.0,96.0
33,miao29,3/12/23,23:41:30,NaN,NaN,0.0,0.0,0.0
34,mpietran,3/15/23,23:58:57,50.0,39.0,3.0,0.0,89.0
35,mtejeda,3/11/23,19:37:13,50.0,37.0,-1.0,0.0,87.0
36,ndullam,3/12/23,20:02:57,50.0,46.0,0.0,0.0,96.0
37,rdelliso,3/12/23,21:49:53,50.0,44.0,0.0,0.0,94.0
38,rnstump,3/14/23,23:48:07,49.0,43.0,2.0,0.0,92.0
39,sharm390,3/16/23,0:01:11,NaN,NaN,4.0,0.0,0.0
40,sharm535,3/12/23,17:07:53,0.0,0.0,0.0,0.0,0.0
41,singh726,3/8/23,20:11:36,49.0,37.0,-4.0,4.0,90.0
42,skharban,3/13/23,23:24:21,50.0,33.0,1.0,0.0,83.0
43,sun1017,3/13/23,22:55:02,50.0,40.0,1.0,0.0,90.0
44,szapodea,3/14/23,19:33:17,50.0,43.0,2.0,0.0,93.0
45,tmattil,3/13/23,23:34:33,49.0,43.0,1.0,0.0,92.0
46,upadhya4,3/12/23,18:59:55,49.0,24.0,0.0,0.0,73.0
47,verma119,3/12/23,23:45:23,NaN,NaN,0.0,0.0,0.0
48,wangej,3/8/23,13:37:15,50.0,46.0,-4.0,4.0,100.0
49,wu1542,3/12/23,20:51:36,50.0,14.0,0.0,0.0,64.0
50,yang1800,3/15/23,16:15:17,50.0,43.0,3.0,0.0,93.0
51,yberg,3/14/23,17:10:39,50.0,45.0,2.0,0.0,95.0
52,yyegorov,3/9/23,20:02:43,49.0,4.0,-3.0,0.0,53.0
53,zhan4150,3/12/23,18:05:54,50.0,48.0,0.0,0.0,98.0
54,zhou977,3/11/23,12:38:37,49.0,44.0,-1.0,0.0,93.0
55,zhu862,3/15/23,23:51:58,2.0,2.0,3.0,0.0,4.0
56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [58]:
p1grades = pd.read_csv("p1.csv")

In [59]:
p1grades

        name  p1 latedays  p1 points
0   aagnihot            0          0
1   abhullar            0         96
2      adusi            0         96
3     agazda            0         94
4   akhorana            0         96
..       ...          ...        ...
63  yyegorov            0         98
64  zhan4150            0         98
65  zheng547            2         98
66   zhou977            0         94
67    zhu862            0         56

[68 rows x 3 columns]

In [60]:
latedays = p1grades.merge(p2grades, on='name', how='outer')

In [61]:
latedays

,name,p1 latedays,p1 points,date,times,points,points %,latedays,bonus,total
0,aagnihot,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,abhullar,0,96,44997.0,0.817986,4.0,8.0,0.0,0.0,8.0
2,adusi,0,96,44992.0,0.506586,48.0,96.0,-5.0,4.0,100.0
3,agazda,0,94,44997.0,0.974919,45.0,90.0,0.0,0.0,90.0
4,akhorana,0,96,44997.0,0.036921,47.0,94.0,0.0,0.0,94.0
...,...,...,...,...,...,...,...,...,...,...
63,yyegorov,0,98,44994.0,0.835220,4.0,8.0,-3.0,0.0,8.0
64,zhan4150,0,98,44997.0,0.754097,48.0,96.0,0.0,0.0,96.0
65,zheng547,2,98,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,zhou977,0,94,44996.0,0.526817,44.0,88.0,-1.0,0.0,88.0
67,zhu862,0,56,45000.0,0.994421,2.0,4.0,3.0,0.0,4.0

In [62]:
latedays.to_csv("p1p2.csv", index=False)

In [5]:
gradesp2 = pd.read_csv("gradesp2.csv")

In [6]:
gradesp2

,name,date,times,syntaxpoints,typepoints,latedays,SRC %,SRC bonus,bonus,old total,total
0,abhullar,3/12/23,19:37:54,50.0,4.0,0,0,0.00,0,54,54.00
1,adusi,3/7/23,12:09:29,50.0,48.0,-5,5,4.90,4,102,106.90
2,agazda,3/12/23,23:23:53,50.0,45.0,0,5,4.75,0,95,99.75
3,akhorana,3/12/23,0:53:10,50.0,47.0,0,5,4.85,0,97,101.85
4,akute,3/8/23,17:49:22,50.0,48.0,-4,5,4.90,4,102,106.90
5,amelachu,3/11/23,16:19:11,50.0,50.0,-1,5,5.00,0,100,105.00
6,aneema,3/10/23,17:35:01,50.0,50.0,-2,5,5.00,0,100,105.00
7,aravadha,3/12/23,21:38:02,50.0,4.0,0,0,0.00,0,54,54.00
8,brupp,3/15/23,23:59:40,50.0,47.0,3,5,4.85,0,97,101.85
9,choi493,3/14/23,22:54:58,16.0,4.0,2,0,0.00,0,20,20.00
10,ding256,3/15/23,22:56:01,50.0,48.0,3,5,4.90,0,98,102.90
11,eafalck,3/8/23,19:21:44,50.0,46.0,-4,5,4.80,4,100,104.80
12,edetoled,3/13/23,23:43:02,46.0,27.0,1,4,2.92,0,73,75.92
13,ehli,3/15/23,23:54:27,50.0,4.0,3,5,2.70,0,54,56.70
14,gala0,3/8/23,20:26:40,50.0,48.0,-4,5,4.90,4,102,106.90
15,gupta565,3/13/23,23:35:51,49.0,36.0,1,5,4.25,0,85,89.25
16,harve106,3/9/23,15:07:31,39.0,18.0,-3,5,2.85,0,57,59.85
17,heise4,3/12/23,23:58:25,46.0,43.0,0,0,0.00,0,89,89.00
18,hsu226,3/12/23,23:50:17,50.0,46.0,0,5,4.80,0,96,100.80
19,ihpatel,3/8/23,17:49:14,50.0,20.0,-4,0,0.00,4,74,74.00
20,jain385,3/8/23,21:52:12,50.0,48.0,-4,5,4.90,4,102,106.90
21,jchustak,3/15/23,23:58:02,50.0,40.0,3,5,4.50,0,90,94.50
22,jensen97,3/15/23,23:53:51,50.0,4.0,3,5,2.70,0,54,56.70
23,jpha,3/15/23,23:57:41,48.0,30.0,3,0,0.00,0,78,78.00
24,kang377,3/12/23,22:26:04,50.0,46.0,0,5,4.80,0,96,100.80
25,kim2942,3/8/23,12:36:50,50.0,50.0,-4,5,5.00,4,104,109.00
26,kong98,3/8/23,22:55:48,50.0,40.0,-4,5,4.50,4,94,98.50
27,lee3380,3/8/23,19:04:25,50.0,44.0,-4,5,4.70,4,98,102.70
28,li3327,3/13/23,21:23:22,2.0,2.0,1,0,0.00,0,4,4.00
29,mason143,3/13/23,22:07:03,50.0,43.0,1,0,0.00,0,93,93.00
30,mccarth,3/12/23,23:22:58,50.0,45.0,0,0,0.00,0,95,95.00
31,mdsantia,3/15/23,23:57:14,50.0,43.0,3,0,0.00,0,93,93.00
32,menonk,3/13/23,20:44:19,50.0,46.0,1,5,4.80,0,96,100.80
33,miao29,3/12/23,23:41:30,NaN,NaN,0,5,0.00,0,0,0.00
34,mpietran,3/15/23,23:58:57,50.0,39.0,3,5,4.45,0,89,93.45
35,mtejeda,3/11/23,19:37:13,50.0,37.0,-1,0,0.00,0,87,87.00
36,ndullam,3/12/23,20:02:57,50.0,46.0,0,5,4.80,0,96,100.80
37,rdelliso,3/12/23,21:49:53,50.0,44.0,0,0,0.00,0,94,94.00
38,rnstump,3/14/23,23:48:07,49.0,43.0,2,5,4.60,0,92,96.60
39,sharm390,3/16/23,0:01:11,NaN,NaN,4,5,0.00,0,0,0.00
40,sharm535,3/12/23,17:07:53,0.0,0.0,0,5,0.00,0,0,0.00
41,shaw133,3/15/23,23:55:00,43.0,4.0,3,5,2.35,0,47,49.35
42,singh726,3/8/23,20:11:36,49.0,37.0,-4,5,4.30,4,90,94.30
43,skharban,3/13/23,23:24:21,50.0,33.0,1,5,4.15,0,83,87.15
44,sun1017,3/13/23,22:55:02,50.0,40.0,1,5,4.50,0,90,94.50
45,szapodea,3/14/23,19:33:17,50.0,43.0,2,5,4.65,0,93,97.65
46,tmattil,3/13/23,23:34:33,49.0,43.0,1,5,4.60,0,92,96.60
47,upadhya4,3/12/23,18:59:55,49.0,24.0,0,5,3.65,0,73,76.65
48,verma119,3/12/23,23:45:23,NaN,NaN,0,5,0.00,0,0,0.00
49,wangej,3/8/23,13:37:15,50.0,46.0,-4,5,4.80,4,100,104.80
50,wu1542,3/12/23,20:51:36,50.0,14.0,0,0,0.00,0,64,64.00
51,yang1800,3/15/23,16:15:17,50.0,43.0,3,5,4.65,0,93,97.65
52,yberg,3/14/23,17:10:39,50.0,45.0,2,5,4.75,0,95,99.75
53,yyegorov,3/9/23,20:02:43,49.0,4.0,-3,0,0.00,0,53,53.00
54,zhan4150,3/12/23,18:05:54,50.0,48.0,0,5,4.90,0,98,102.90
55,zhou977,3/11/23,12:38:37,49.0,44.0,-1,5,4.65,0,93,97.65
56,zhu862,3/15/23,23:51:58,2.0,2.0,3,5,0.20,0,4,4.20

In [7]:
unamesp2 = pd.read_csv("unamesp2.csv")

In [8]:
unamesp2["name"] = unamesp2["name"].apply(lambda x: x[1:])

In [9]:
unamesp2

                                     name  Last Name First Name
0                                aagnihot  Agnihotri     Aniket
1                                abhullar    Bhullar      Advit
2                                   adusi       Dusi    Abhinav
3                                  agazda      Gazda     Andrew
4                                akhorana    Khorana      Arjun
..                                    ...        ...        ...
62                               zhan4150      Zhang      Brian
63                               zheng547      Zheng       Kyle
64                                zhou977       Zhou  Christine
65                                 zhu862        Zhu   Benjamin
66  ZZDemo.Student.wl.202320.CS.35200.LE1  ZZStudent     ZZDemo

[67 rows x 3 columns]

In [10]:
mergednames = unamesp2.merge(gradesp2, on='name', how='outer')

In [11]:
mergednames

,name,Last Name,First Name,date,times,syntaxpoints,typepoints,latedays,SRC %,SRC bonus,bonus,old total,total
0,aagnihot,Agnihotri,Aniket,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,abhullar,Bhullar,Advit,3/12/23,19:37:54,50.0,4.0,0.0,0.0,0.00,0.0,54.0,54.00
2,adusi,Dusi,Abhinav,3/7/23,12:09:29,50.0,48.0,-5.0,5.0,4.90,4.0,102.0,106.90
3,agazda,Gazda,Andrew,3/12/23,23:23:53,50.0,45.0,0.0,5.0,4.75,0.0,95.0,99.75
4,akhorana,Khorana,Arjun,3/12/23,0:53:10,50.0,47.0,0.0,5.0,4.85,0.0,97.0,101.85
...,...,...,...,...,...,...,...,...,...,...,...,...,...
62,zhan4150,Zhang,Brian,3/12/23,18:05:54,50.0,48.0,0.0,5.0,4.90,0.0,98.0,102.90
63,zheng547,Zheng,Kyle,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,zhou977,Zhou,Christine,3/11/23,12:38:37,49.0,44.0,-1.0,5.0,4.65,0.0,93.0,97.65
65,zhu862,Zhu,Benjamin,3/15/23,23:51:58,2.0,2.0,3.0,5.0,0.20,0.0,4.0,4.20
66,ZZDemo.Student.wl.202320.CS.35200.LE1,ZZStudent,ZZDemo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
mergednames.to_csv("mergednames.csv", index=False)